### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by unikzforce** [arnaudhb/docker-fahclient#3]
would you please keep the docker updated to the latest version?

**Comment by sgnsajgon** [comment]
`docker pull arnaudhb/docker-fahclient:7.5.1`

Not work, because the latest Docker image is not deployed on Docker Hub.

**Comment by arnaudhb** [comment]
Done.

docker-compose usage broke automated build with Docker Hub.

I just pushed the images myself (latest + 7.6.21 tag).

Enjoy.
